<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ris="http://zakupki.gov.ru/fz44/get-docs-ris/ws" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://zakupki.gov.ru/oos/base/1" targetNamespace="http://zakupki.gov.ru/fz44/get-docs-ris/ws">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://zakupki.gov.ru/fz44/get-docs-ris/ws" schemaLocation="../getDocsRIS-ws-api.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="getDocsRisRequest">
		<wsdl:part name="getDocsRisRequest" element="ris:getDocsRisRequest"/>
	</wsdl:message>
	<wsdl:message name="getDocsRisResponse">
		<wsdl:part name="getDocsRisResponse" element="ris:getDocsRisResponse"/>
	</wsdl:message>
	<wsdl:portType name="GetDocsPortType">
		<wsdl:operation name="getDocsRis">
			<wsdl:input name="getDocsRisRequest" message="ris:getDocsRisRequest"/>
			<wsdl:output name="getDocsRisResponse" message="ris:getDocsRisResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="GetDocsPortTypeSoap11" type="ris:GetDocsPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getDocsRis">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/queue/ws/get-docs-ris"/>
			<wsdl:input name="getDocsRisRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getDocsRisResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="GetDocsPortTypeService">
		<wsdl:port name="GetDocsPortTypeSoap11" binding="ris:GetDocsPortTypeSoap11">
			<soap:address location="${serviceLocation}"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
