<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:org="http://zakupki.gov.ru/fz44/get-docs-org/ws" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://zakupki.gov.ru/oos/base/1" targetNamespace="http://zakupki.gov.ru/fz44/get-docs-org/ws">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://zakupki.gov.ru/fz44/get-docs-org/ws" schemaLocation="../getDocsOrganization-ws-api.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="getDocsOrgRequest">
		<wsdl:part name="getDocsOrgRequest" element="org:getDocsOrgRequest"/>
	</wsdl:message>
	<wsdl:message name="getDocsOrgResponse">
		<wsdl:part name="getDocsOrgResponse" element="org:getDocsOrgResponse"/>
	</wsdl:message>
	<wsdl:portType name="GetDocsPortType">
		<wsdl:operation name="getDocsOrg">
			<wsdl:input name="getDocsOrgRequest" message="org:getDocsOrgRequest"/>
			<wsdl:output name="getDocsOrgResponse" message="org:getDocsOrgResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="GetDocsPortTypeSoap11" type="org:GetDocsPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getDocsOrg">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/queue/ws/get-docs-org"/>
			<wsdl:input name="getDocsOrgRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getDocsOrgResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="GetDocsPortTypeService">
		<wsdl:port name="GetDocsPortTypeSoap11" binding="org:GetDocsPortTypeSoap11">
			<soap:address location="${serviceLocation}"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
